expose_php = Off
memory_limit = 256M
post_max_size = 22M
upload_max_filesize = 20M
max_execution_time = 120

session.use_strict_mode = 1
session.cookie_httponly = 1
session.cookie_samesite = Lax

opcache.enable = 1
opcache.enable_cli = 1
opcache.validate_timestamps = 0
opcache.memory_consumption = 128
opcache.max_accelerated_files = 10000
